function models = train_shallow_classifiers(X,y)
%TRAIN_SHALLOW_CLASSIFIERS Manuscript classifier configurations.

y=categorical(y);

models.kNN = fitcknn(X,y, ...
    "NumNeighbors",1,"Distance","cityblock", ...
    "DistanceWeight","equal","Standardize",true);

models.SVM = fitcsvm(X,y, ...
    "KernelFunction","polynomial","PolynomialOrder",3, ...
    "BoxConstraint",1,"KernelScale","auto", ...
    "Standardize",true);

models.DT = fitctree(X,y, ...
    "MaxNumSplits",20,"SplitCriterion","gdi");

models.LD = fitcdiscr(X,y, ...
    "DiscrimType","linear","Gamma",0);

models.NB = fitcnb(X,y, ...
    "DistributionNames","kernel","Kernel","normal");

models.LR = fitclinear(X,y, ...
    "Learner","logistic","Regularization","none");
end
