function [net,info] = train_holdout(trainImds,valImds,cfg)
%TRAIN_HOLDOUT Train NegativeKANNeXt with the manuscript settings.

rng(cfg.Seed,"twister");

trainDS = augmentedImageDatastore(cfg.InputSize(1:2),trainImds, ...
    "ColorPreprocessing","gray2rgb");
valDS = augmentedImageDatastore(cfg.InputSize(1:2),valImds, ...
    "ColorPreprocessing","gray2rgb");

lgraph = buildNegativeKANNeXt(cfg);

opts = trainingOptions("sgdm", ...
    "InitialLearnRate",cfg.Training.InitialLearnRate, ...
    "Momentum",cfg.Training.Momentum, ...
    "L2Regularization",cfg.Training.L2Regularization, ...
    "MiniBatchSize",cfg.Training.MiniBatchSize, ...
    "MaxEpochs",cfg.Training.MaxEpochs, ...
    "LearnRateSchedule","none", ...
    "Shuffle","every-epoch", ...
    "ValidationData",valDS, ...
    "ValidationFrequency",cfg.Training.ValidationFrequency, ...
    "ValidationPatience",Inf, ...
    "GradientThreshold",Inf, ...
    "ExecutionEnvironment",cfg.Training.ExecutionEnvironment, ...
    "Verbose",cfg.Training.Verbose, ...
    "Plots",cfg.Training.Plots);

[net,info] = trainNetwork(trainDS,lgraph,opts);
end
